#' #' all parameters descriptions.
#' ParamDescript <- list(
#' ###############################################################################",
#' LAPSE_RATE = "temperature lapse rate in C/m",
#' ###############################################################################",
#'
#' ###############################################################################",
#' ALBEDO_BARE_SOIL = "albedo for bare soil",
#'
#' EMISS_GRND = "Ground emissivity",
#' EMISS_VEG = "Veg emissivity",
#' EMISS_ICE = "Ice emissivity",
#' EMISS_SNOW = "Snow emissivity",
#' EMISS_H2O = "Emissivity of open water surface",
#' ###############################################################################",
#'
#' ###############################################################################",
#' # Physical Constraints",
#' SOIL_RESID_MOIST = "define residual moisture content of soil column",
#' SOIL_SLAB_MOIST_FRACT = "Volumetric moisture content (fraction of porosity)",
#' # in the soil/rock below the bottom soil layer; this",
#' # assumes that the soil below the bottom layer has",
#' # the same texture as the bottom layer.",
#'
#' VEG_LIQUID_WATER_CAPACITY = "water holding capacity of snow as a fraction of snow-water-equivalent",
#' VEG_LAI_SNOW_MULTIPLIER = "multiplier to calculate the amount of available snow interception as a function of LAI (m)",
#' VEG_MIN_INTERCEPTION_STORAGE = "the amount of snow on the canopy that can only be melted off. (m)",
#' VEG_RATIO_DH_HEIGHT = "Ratio of displacement height (m) to vegetation height (m)",
#' VEG_RATIO_RL_HEIGHT = "Ratio of roughness length (m) to vegetation height (m)",
#' VEG_LAI_WATER_FACTOR = "Coefficient multiplied by the LAI to determine the amount of water that can be stored in the canopy",
#' ###############################################################################",
#'
#' ###############################################################################",
#' # Canopy Resistance Parameters",
#' CANOPY_CLOSURE = "Threshold vapor pressure deficit for stomatal closure (Pa)",
#' CANOPY_RSMAX = "Maximum allowable resistance (s/m)",
#' CANOPY_VPDMINFACTOR = "Minimum allowable vapor pressure deficit factor",
#' ###############################################################################",
#'
#' ###############################################################################",
#' # Lake Model Parameters",
#'
#' # lake model related constants",
#' LAKE_TMELT = "no description",
#' LAKE_MAX_SURFACE = "max. surface layer thickness for E-B (m)",
#' LAKE_BETA = "Curve shape parameter for lake profile.",
#' LAKE_FRACMIN = "min ice thickness in meters",
#' LAKE_FRACLIM = "lower limit on fractional ice cover",
#' LAKE_DM = "molecular diffusivity of water",
#' LAKE_SNOWCRIT = "for albedo, in m",
#' LAKE_ZWATER = "0.004 - original value",
#' LAKE_ZSNOW = "no description",
#' LAKE_RHOSNOW = "densities snow on ice",
#' LAKE_CONDI = "thermal conductivity of ice",
#' LAKE_CONDS = "thermal conductivity of snow",
#'
#' # attenuation of short and longwave radiation through ice (1/m)",
#' LAKE_LAMISW = "1.5 in Patterson & Hamblin",
#' LAKE_LAMILW = "20.0 in Patterson & Hamblin",
#'
#' # attenuation of short and longwave radiation through snow (1/m)",
#' LAKE_LAMSSW = "6.0 in Patterson & Hamblin",
#' LAKE_LAMSLW = "20.0 in Patterson & Hamblin",
#'
#' # attenuation of short and longwave radiation through water (1/m)",
#' LAKE_LAMWSW = "San Fran Bay data: 0.31 - 29.9 1/m (visible)",
#' LAKE_LAMWLW = "Hostetler and Bartlein assume 0.85 1/m (total)",
#' LAKE_A1 = "Fraction of radiation in visible band.",
#' LAKE_A2 = "Fraction of radiation in infrared band.",
#' LAKE_QWTAU = "D. Pollard sub-ice time constant. (86400. / 2.)",
#' ###############################################################################",
#'
#' ###############################################################################",
#' # Saturated Vapor Pressure Curve Parameters",
#' SVP_A = "Saturated Vapor Pressure Curve Parameters",
#' SVP_B = "Saturated Vapor Pressure Curve Parameters",
#' SVP_C = "Saturated Vapor Pressure Curve Parameters",
#' ###############################################################################",
#'
#' ###############################################################################",
#' # Carbon Cycling constants",
#' CARBON_CATMCURRENT = "Current global atmospheric CO2 mixing ratio (ppm)",
#' CARBON_SW2PAR = "Empirical ratio of PAR [W/m2] to SHORTWAVE [W/m2] from Lopez et al., 2001",
#' ###############################################################################",
#'
#' ###############################################################################",
#' # Photosynthesis Parameters",
#' PHOTO_OMEGA = "single leaf scattering albedo",
#' PHOTO_LAIMAX = "Maximum LAI in nitrogen scaling",
#' PHOTO_LAILIMIT = "Minimum LAI in nitrogen scaling and maximum LAI in PAR",
#' # computation",
#' PHOTO_LAIMIN = "Minimum LAI in PAR computation",
#' PHOTO_EPAR = "Energy content of PAR [J/mol photons]",
#' # = (4.6 mol/MJ PAR)^-1, #",
#' PHOTO_FCMAX = "Maximum fractional veg cover",
#' # (1-FcMax) = min amount of ground visible",
#' PHOTO_FCMIN = "Minimum fractional veg cover",
#' # (1-FcMin) = max amount of ground visible",
#' PHOTO_ZENITHMIN = "Check for solar zenith angle > 89 deg",
#' PHOTO_ZENITHMINPAR = "Cosine of the minimum solar zenith angle for",
#' # photosynthesis to take place",
#' PHOTO_ALBSOIPARMIN = "Minimum soil reflectivity in PAR range",
#' PHOTO_MINMAXETRANS = "Minimum of maximum electron transport rate",
#' # [10e-12 mol/(m^2 s)]",
#' PHOTO_MINSTOMCOND = "Minimum stomatal conductance [mol H2O/m2s]",
#'
#' # Factors that relate leaf internal CO2 concentration to ambient CO2, #",
#' # concentration",
#' PHOTO_FCI1C3 = "C3 Plants",
#' PHOTO_FCI1C4 = "C4 Plants",
#'
#' # C3 PLANTS: FARQUHAR, G.D., S. VON CAEMMERER AND J.A. BERRY, = 1980. A",
#' # BIOCHEMICAL MODEL OF PHOTOYNTHESIS IN LEAVES OF C3 SPECIES. PLANTA = 149,",
#' # = 78-90.",
#' PHOTO_OX = "OXYGEN CONCENTRATION [MOL(O2) / MOL(AIR)]",
#' PHOTO_KC0 = "MICHAELIS-MENTEN CONSTANT FOR CO2 AT 25C",
#' #  [MOL(CO2) / MOL(AIR)]",
#' PHOTO_KO0 = "MICHAELIS-MENTEN CONSTANT FOR O2 AT 25C",
#' # [MOL(O2) / MOL(AIR)]",
#' PHOTO_EC = "ACTIVATION ENERGY FOR KC [J / MOL]",
#' PHOTO_EO = "ACTIVATION ENERGY FOR KO [J / MOL]",
#' PHOTO_EV = "ACTIVATION ENERGY FOR VCMAX [J / MOL]",
#' PHOTO_ER = "ACTIVATION ENERGY FOR DARK RESPIRATION [J / MOL]",
#' PHOTO_ALC3 = "EFFICIENCY OF OF PHOTON CAPTURE",
#' PHOTO_FRDC3 = "RATIO OF DARK RESPIRATION TO \"PVM\" AT 25C for C3",
#'
#' # C4 PLANTS: COLLATZ, G.J., M. RIBAS-CARBO AND J.A. BERRY, = 1992.  COUPLED",
#' # PHOTOSYNTHESIS-STOMATAL CONDUCTANCE MODEL FOR LEAVES OF C4 PLANTS. AUST. J.",
#' # PLANT PHYSIOL. = 19, 519-538.",
#' PHOTO_EK = "Q10=2 (Collatz et al. 1992)",
#' PHOTO_ALC4 = "EFFECTIVE QUANTUM EFFICIENCY",
#' PHOTO_FRDC4 = "RATIO OF DARK RESPIRATION TO \"PVM\" AT 25C for C4",
#' PHOTO_THETA = "CURVATURE PARAMETER",
#'
#' # Plant Maintenance and Growth Respiration Parameters",
#' PHOTO_FRLEAF = "Ratio of canopy leaf respiration to whole plant",
#' # maintenance respiration",
#' PHOTO_FRGROWTH = "Ratio of plant growth respiration to NPP",
#' ###############################################################################",
#'
#' ###############################################################################",
#' # Soil Respiration Parameters",
#' SRESP_E0_LT = "Lloyd-Taylor E0 parameter [K]",
#' SRESP_T0_LT = "Lloyd-Taylor T0 parameter [K]",
#' SRESP_WMINFM = "minimum soil moisture (fraction) at which soil",
#' # respiration can occur",
#' SRESP_WMAXFM = "maximum soil moisture (fraction) at which soil",
#' # respiration can occur",
#' SRESP_WOPTFM = "soil moisture (fraction) at which maximum soil",
#' # respiration occurs",
#' SRESP_RHSAT = "ratio of soil respiration rate under saturated conditions",
#' # (w=wmaxFM) to that under optimal conditions (w=woptFM)",
#' SRESP_RFACTOR = "scaling factor to account for other (non-moisture)",
#' # sources of inhibition of respiration",
#' SRESP_TAULITTER = "Litter pool turnover time [y]",
#' SRESP_TAUINTER = "Intermediate pool turnover time [y]",
#' SRESP_TAUSLOW = "Slow pool turnover time [y]",
#' SRESP_FAIR = "Fraction of respired carbon from litter pool that is lost",
#' # to atmosphere",
#' SRESP_FINTER = "Fraction of [respired carbon from litter pool that goes",
#' # to soil] that goes to intermediate pool",
#' ###############################################################################",
#'
#' ###############################################################################",
#' # Iteration bracket widths",
#' SNOW_DT = "Used to bracket snow surface temperatures while computing the",
#' # snow surface energy balance (C)",
#' SURF_DT = "Used to bracket soil surface temperatures while computing",
#' # energy balance (C)",
#' SOIL_DT = "Used to bracket soil temperatures while solving the soil",
#' # thermal flux (C)",
#' CANOPY_DT = "Used to bracket canopy air temperatures while computing",
#' #energy balance (C)",
#' CANOPY_VP = "Used to bracket canopy vapor pressures while computing",
#' # moisture balance (Pa)",
#' ###############################################################################",
#'
#' ###############################################################################",
#' # Snow Parameters",
#' SNOW_MAX_SURFACE_SWE = "maximum depth of the surface layer in water equivalent (m) [default = 0.125]",
#' SNOW_NEW_SNOW_DENSITY = "density of new fallen snow [50]",
#' SNOW_DENS_DMLIMIT = "Density limit used in calculation of destructive metamorphism(kg/m^3)",
#' SNOW_DENS_MAX_CHANGE = "maximum change in snowfall depth (fraction of swe)",
#'
#' # Constants in snow density computation",
#' SNOW_DENS_ETA0 = "viscosity of snow at T=0C and density = 0",
#' # used in calculation of true viscosity (Ns/m2)",
#' SNOW_DENS_C1 = "used in calculation of true viscosity (Ns/m2)",
#' SNOW_DENS_C2 = "used in calculation of true viscosity (Ns/m2)",
#' SNOW_DENS_C5 = "constant used in snow viscosity calculation, taken from",
#' SNOW_DENS_C3 = "Constant in snow density computation",
#' SNOW_DENS_C3_CONST = "Constant in snow density computation",  ## "Constant in snow density computation "
#' SNOW_DENS_C4 = "Constant in snow density computation",
#' SNOW_DENS_C4WET = "Constant in snow density computation",   ## Constant in snow density computation
#' # SNTHRM.89 (/C)",
#' SNOW_DENS_C6 = "constant used in snow viscosity calculation, taken from",
#' # SNTHRM.89 (kg/m3)",
#' SNOW_DENS_F = "internal compaction rate coefficient",
#' SNOW_DENS_EXP = "exponent in snow density compaction equation [Bras pg. 257 ]",
#' SNOW_DENS_DENOM = "denomenator in snow density compaction equation [Bras pg. 257]" ,
#' SNOW_NEW_BRAS_DENOM = "Constant in Bras new snow density computation.",
#'
#' # Minimum SWQ for which the snowpack energy balance is computed independent of",
#' # the soil surface temperature",
#' SNOW_MIN_SWQ_EB_THRES = "no description",
#'
#' # Attenuation coefficients for shortwave in a snowpack.  Values and equation",
#' # taken from Patterson and Hamblin, = "no description",
#' SNOW_A1 = "no description",
#' SNOW_A2 = "no description",
#' SNOW_L1 = "(1/m)",
#' SNOW_L2 = "(1/m)",
#'
#' # Snow albedo curve parameters.  Defaults are from Bras p263. Should not be",
#' # changed except for serious problems with snow melt",
#' SNOW_NEW_SNOW_ALB = "no description",
#' SNOW_ALB_ACCUM_A = "no description",
#' SNOW_ALB_ACCUM_B = "no description",
#' SNOW_ALB_THAW_A = "no description",
#' SNOW_ALB_THAW_B = "no description",
#'
#' # Defines the minimum amount of new snow (mm) which will reset the snowpack",
#' # albedo to new snow",
#' SNOW_TRACESNOW = "no description",
#' MIN_SNOW_WETFRAC = "Minimum fraction of snow depth to be considered wet.",
#'
#' # new snow density max for Hedstrom and Pomeroy 1998 equation
#' SNOW_NEW_SNOW_DENS_MAX = "new snow density max for Hedstrom and Pomeroy 1998 equation",
#' SNOW_NEW_SNT_C1 = "Constant in Sntherm new snow density computation.",  ##
#' SNOW_NEW_SNT_C2 = "Constant in Sntherm new snow density computation.",  ## Constant in Sntherm new snow density computation.
#' SNOW_NEW_SNT_C3 = "Constant in Sntherm new snow density computation.",  ## Constant in Sntherm new snow density computation.
#' # snow temperature
#' SNOW_MAX_SNOW_TEMP = "maximum temperature (C) at which snow can fall",  ## maximum temperature (C) at which snow can fall
#' SNOW_MIN_RAIN_TEMP = "minimum temperature (C) at which rain can fall",  ## minimum temperature (C) at which rain can fall
#'
#' SNOW_DENS_DMLIMIT_FACTOR = "Density limit factor used in calculation of destructive metamorphism (kg/m^3)",
#' SNOW_DEPTH_THRES = "Snow depth threshold below which we do not consider the ground flux out of the snowpack in calculating change in cold content (m)",
#' SNOW_CONDUCT = "conductivity of snow (W/mK)",
#' SNOW_LIQUID_WATER_CAPACITY = "water holding capacity of snow as a fraction of snow-water-equivalent",
#' HUGE_RESIST = "Extermely large resistance term (s/m)",
#' ###############################################################################",
#'
#' ###############################################################################",
#' # Blowing Snow Parameters",
#' BLOWING_KA = "thermal conductivity of air (W/mK)",
#' BLOWING_CSALT = "saltation constant m/s",
#' BLOWING_UTHRESH = "threshold shear velocity m/s",
#' BLOWING_KIN_VIS = "Kinemativ viscosity of air (m2/s)",
#' BLOWING_MAX_ITER = "Max. iterations for numerical integration",
#' BLOWING_K = "no description",
#' BLOWING_MACHEPS = "Accuracy tolerance for numerical integration",
#' BLOWING_SETTLING = "Particle settling velocity m/s",
#' BLOWING_NUMINCS = "Number of prob intervals to solve for wind.",
#' ###############################################################################",
#'
#' ###############################################################################",
#' # July average temperature for tree line",
#' TREELINE_TEMPERATURE = "no description",
#'
#' ###############################################################################
#' # options for Snow.VIC
#' BLOWING_CALC_PROB = "no description",
#' BLOWING_FETCH = "no description",
#' BLOWING_SIMPLE = "no description",
#' BLOWING_SPATIAL_WIND = "no description",
#' BLOWING_VAR_THRESHOLD = "no description",
#' SPATIAL_SNOW = "no description"
#' )
#' use_data(ParamDescript, overwrite = TRUE)
