# ## write txt ####
# # Unit_dataset <- Pre_dataset
# # n_Grp <- as.numeric(map(Unit_dataset, length))
# # Group_Name <- reduce(map2(names(Unit_dataset), n_Grp, rep), c)
# # Variable_Name <- reduce(map(Unit_dataset, names), c)
# # df_Grp <- data.frame(Group = Group_Name, Variable = Variable_Name)
# # string = paste0('Unit_dataset$',df_Grp$Group, '$', df_Grp$Variable, ' = \'abc\'')
# # write(string, 'temp_write.txt')
#
# ## write the Units ####
# Unit_dataset <- list()
# Unit_dataset$Evatrans$RET = 'mm'
# Unit_dataset$Evatrans$EvaporationCanopy = 'mm'
# Unit_dataset$Evatrans$AET = 'mm'
# Unit_dataset$Evatrans$Transpiration = 'mm'
# Unit_dataset$Evatrans$EvaporationLand = 'mm'
# Unit_dataset$Ground$MoistureVolume = 'mm'
# Unit_dataset$Ground$MoistureCapacityMax = 'mm'
# Unit_dataset$Ground$ZoneMoistureVolume = 'mm'
# Unit_dataset$Ground$ZoneDepth = 'mm'
# Unit_dataset$Ground$BaseFlow = 'mm'
# Unit_dataset$Ground$MoistureCapacity = 'mm'
# Unit_dataset$Ground$Depth = 'mm'
# Unit_dataset$Ground$Overflow = 'mm'
# Unit_dataset$Ground$Runoff = 'mm'
# Unit_dataset$Prec$Precipitation = 'mm'
# Unit_dataset$Prec$SnowFall = 'mm'
# Unit_dataset$Prec$RainFall = 'mm'
# Unit_dataset$Aerodyna$AerodynaResist = 's/m'
# Unit_dataset$Aerodyna$ArchitecturalResist = 's/m'
# Unit_dataset$Aerodyna$StomatalResist = 's/m'
# Unit_dataset$Canopy$StorageCapacity = 'mm'
# Unit_dataset$Intercept$Interception = 'mm'
# Unit_dataset$Infilt$Infiltration = 'mm'
# Unit_dataset$Infilt$InfiltrationRat = 'mm'
# Unit_dataset$Infilt$InfiltrationRateMax = 'mm'
# Unit_dataset$SoilData$Porosity = '100%'
# Unit_dataset$SoilData$SaturatedConductivity = 'm/s'
# Unit_dataset$SoilData$Conductivity = 'm/s'
# Unit_dataset$SoilData$WettingFrontSuction = 'm/s'
# Unit_dataset$MetData$TAir = 'Cel'
# Unit_dataset$MetData$TMax = 'Cel'
# Unit_dataset$MetData$TMin = 'Cel'
# Unit_dataset$MetData$Actual_vapor_press = 'mPa'
# Unit_dataset$MetData$RelativeHumidity = '%'
# Unit_dataset$MetData$WindSpeed = 'm/s'
# Unit_dataset$MetData$WindH = 'm'
# Unit_dataset$MetData$SunHour = 'h'
# Unit_dataset$GeoData$Latitude = 'deg'
# Unit_dataset$GeoData$Elevation = 'm'
# Unit_dataset$TimeData$NDay = '--'
# Unit_dataset$Route$WaterSource = 'mm'
# Unit_dataset$Route$UHAll = '--'
# Unit_dataset$Route$TypeGridID = '--'
# Unit_dataset$Route$TransAll = '--'
# Unit_dataset$Route$Store = 'mm'
# Unit_dataset$Route$Gr4j_UH1 = '--'
# Unit_dataset$Route$Gr4j_UH2 = '--'
# Unit_dataset$Route$StaFlow = 'm3/s'
# Unit_dataset$Snow$Ice_Volume = 'mm'
# Unit_dataset$Snow$Liquid_Volume = 'mm'
# Unit_dataset$Snow$SN17_ATI = '--'
# Unit_dataset$Snow$SN17_HD = 'mm'
# Unit_dataset$Snow$Volume = 'mm'
